name: CI

env:
  BUILD_TYPE: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update system
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install libcurl4-openssl-dev libjson-c-dev libarchive-dev cmake make

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Get environment feedback
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./polecat env