name: CI

env:
  BUILD_TYPE: Release

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update system
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install libcurl4-openssl-dev libjson-c-dev libarchive-dev cmake make

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -DBUILD_MOCK:BOOL=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test `wine list`
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./polecat_mock wine list

    - name: Test `wine download`
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./polecat_mock wine download mock

    - name: Test `wine run`
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./polecat_mock wine run mock 1 2 3 4

    - name: Test `lutris search`
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./polecat_mock lutris search game

    - name: Get mock environment
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./polecat_mock env

    - name: Get environment
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./polecat env